package com.cedervs.worlddiscovery.feature.map

import com.cedervs.worlddiscovery.core.discovery.Coordinate
import com.cedervs.worlddiscovery.core.discovery.GeographicPolygon
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * **PHYSICAL PROTOTYPE, Option F/G3 — rendering geometry, deliberately separate from
 * classification.** The on-disk shape of `geo/france-mainland-osm-render.json` — an OSM-derived
 * (relation 1403916, via `polygons.openstreetmap.fr`) mainland-France polygon, validated against
 * real deployed OpenMapTiles boundary tiles (point-to-segment median 6–15m at Geneva/Spain/Italy/
 * Andorra/Monaco — see the Phase G/G2 design-review record, not yet transcribed into `/docs`) and
 * bundled here purely so the visited-country **fill** visually extends much closer to the already
 * physically-validated `basemap-aligned-france-border-prototype` LineLayer than the classification
 * (geoBoundaries) polygon does.
 *
 * **Deliberately NOT [com.cedervs.worlddiscovery.core.discovery.GeographicAreaReferenceJson].**
 * That type is classification's own on-disk shape, owned by `core-discovery-engine`, parsed into a
 * full [com.cedervs.worlddiscovery.core.discovery.GeographicArea] with an `id`/`type`/`parentId`/
 * component structure that carries real classification meaning — `country:FR`'s components are what
 * `ClassifyDiscoveredCellsByGeographicAreaComponents` tests real discoveries against. Reusing that
 * type (or wrapping this artifact in a fake single-component `GeographicArea`) would let a rendering
 * concern silently masquerade as a classification fact somewhere down the line. This type carries
 * only a single [GeographicPolygon]'s worth of coordinates plus provenance — nothing that looks like
 * an area id, a component index, or anything [ClassifyDiscoveredCellsByGeographicAreaComponents]
 * could mistake for classification input. Mainland's *visited status* still always comes from the
 * real classification component (see [countryOverlayFeatureCollection]) — this artifact only ever
 * changes what shape gets drawn once that status is already known to be true.
 *
 * Generated by `tools/geo/GenerateFranceOsmRenderingPolygon.kt` — see that file's own doc comment
 * and `tools/geo/README.md` for the exact reproducible retrieval/regeneration steps.
 */
@Serializable
internal data class MainlandFranceRenderingPolygonJson(
    val sourceId: String,
    val sourceVersion: String,
    val sourceProvenance: String,
    val generatedAt: String,
    val license: String,
    /** Single Polygon -> Ring -> [longitude, latitude]. `polygon[0]` is the outer ring; any further
     * rings are holes. Deliberately never a MultiPolygon/component list — this artifact represents
     * mainland France's rendering geometry only, never Corsica or French Guiana. */
    val polygon: List<List<List<Double>>>,
)

/**
 * Parses [json] into a plain [GeographicPolygon] — the same generic geometry type already used for
 * classification's own [GeographicPolygon], but constructed here from a wholly separate resource,
 * parser, and JSON schema. Never returns anything resembling a [com.cedervs.worlddiscovery.core.discovery.GeographicArea].
 *
 * **Strict on ring closure — a deliberate, narrower contract than [GeographicPolygon] itself
 * enforces.** [GeographicPolygon] only requires 3+ points per ring (it's a generic geometry type
 * also used by classification, where closure isn't assumed — see `CountryOverlayRendering.kt`'s own
 * `toMapLibrePolygon()`, which defensively closes an open ring at *render* time). This artifact is
 * always machine-generated by `tools/geo/GenerateFranceOsmRenderingPolygon.kt`, which always emits
 * closed rings — so an unclosed or too-short ring here can only mean a corrupted or hand-edited
 * resource, which must fail loudly at parse time, never be silently closed. If `GeographicPolygon`'s
 * own downstream closing behavior masked that, a real generator/resource bug could go unnoticed.
 */
internal fun parseMainlandFranceRenderingPolygon(json: String): GeographicPolygon {
    val parsed = Json.decodeFromString<MainlandFranceRenderingPolygonJson>(json)
    return GeographicPolygon(
        rings = parsed.polygon.map { ring ->
            require(ring.size >= 4) {
                "Ring has only ${ring.size} point(s); a valid closed polygon ring needs at least " +
                    "4 (3 distinct corners + the closing repeat)"
            }
            require(ring.first() == ring.last()) {
                "Ring is not closed: first=${ring.first()} last=${ring.last()} -- this parser " +
                    "requires an explicitly closed ring and never silently closes malformed source data"
            }
            ring.map { point ->
                require(point.size == 2) { "Expected [longitude, latitude], got $point" }
                Coordinate(latitude = point[1], longitude = point[0])
            }
        },
    )
}

/** Loads the bundled `geo/france-mainland-osm-render.json` resource — reads from this class's own
 * classloader, mirroring `loadFranceGeographicAreaReference()`'s own established trick (works
 * identically from a plain JVM test and from the real Android app: `feature-map`'s compiled
 * `src/main/resources` end up on the app's classpath the same way its compiled classes do, no
 * separate Android `assets/` copy needed). */
internal fun loadMainlandFranceRenderingPolygon(): GeographicPolygon {
    val resourceStream = object {}.javaClass.getResourceAsStream("/geo/france-mainland-osm-render.json")
        ?: error("geo/france-mainland-osm-render.json resource not found on the classpath")
    val json = resourceStream.use { it.readBytes().toString(Charsets.UTF_8) }
    return parseMainlandFranceRenderingPolygon(json)
}

/** Lazily loaded once, reused across every `applyCountryOverlay` call — parsing ~14k coordinate
 * pairs on every visited-status change would be wasteful; the underlying resource never changes at
 * runtime. */
internal val mainlandFranceRenderingPolygon: GeographicPolygon by lazy { loadMainlandFranceRenderingPolygon() }
